services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_USER}
      POSTGRES_USER: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_NAME}
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/libs/postgresql/data

volumes:
  pgdata: